import 'dart:ui';
import 'package:flutter/material.dart';

String _appTheme = "";

class ThemeHelper {
  Map<String, PrimaryTheme> _supportedThemes = {
    "primary": PrimaryTheme(),
    "secondary": SecondaryTheme(),
  };

  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
    Get.forceAppUpdate();
  }

  PrimaryTheme _getDefaultTheme() {
    //return default strings if locale is not set
    if (_appTheme.isEmpty) {
      return PrimaryTheme();
    }

    //throw exception to notify given local is not found or not generated by the generator
    if (!_supportedThemes.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this locale in JSON file Try running flutter pub run build_runner");
    }

    //return locale from map
    return _supportedThemes[_appTheme] ?? PrimaryTheme();
  }

  PrimaryTheme theme() => _getDefaultTheme();
}

class PrimaryTheme {
  Color get gray700 => fromHex("#705b5b");
  Color get gray400 => fromHex("#bcb5b5");
  Color get gray500 => fromHex("#9a9a9a");
  Color get gray900 => fromHex("#14171e");
  Color get red400 => fromHex("#d35050");
  Color get green700 => fromHex("#369326");
  Color get green500 => fromHex("#39c859");
  Color get green50001 => fromHex("#39c758");
  Color get indigo400 => fromHex("#5a7cda");
  Color get black900 => fromHex("#000000");
  Color get bluegray400 => fromHex("#888888");
  Color get whiteA700 => fromHex("#ffffff");
  Color get gray70001 => fromHex("#665656");
}

class SecondaryTheme extends PrimaryTheme {
  Color get gray700 => fromHex("#705b5b");
  Color get gray400 => fromHex("#bcb5b5");
  Color get gray500 => fromHex("#9a9a9a");
  Color get gray900 => fromHex("#14171e");
  Color get red400 => fromHex("#d35050");
  Color get green700 => fromHex("#369326");
  Color get green500 => fromHex("#39c859");
  Color get green50001 => fromHex("#39c758");
  Color get indigo400 => fromHex("#5a7cda");
  Color get black900 => fromHex("#000000");
  Color get bluegray400 => fromHex("#888888");
  Color get whiteA700 => fromHex("#ffffff");
  Color get gray70001 => fromHex("#665656");
}

PrimaryTheme get appTheme => ThemeHelper().theme();
Color fromHex(String hexString) {
  final buffer = StringBuffer();
  if (hexString.length == 6 || hexString.length == 7) buffer.write('ff');
  buffer.write(hexString.replaceFirst('#', ''));
  return Color(int.parse(buffer.toString(), radix: 16));
}
